const fs = require("fs");
const path = require("path");

async function main() {
  const AuditConsentRegistry = await ethers.getContractFactory("AuditConsentRegistry");
  const registry = await AuditConsentRegistry.deploy();
  await registry.waitForDeployment();

  const address = await registry.getAddress();
  const network = await ethers.provider.getNetwork();

  const deployment = {
    contract: "AuditConsentRegistry",
    address,
    chainId: Number(network.chainId),
    rpcUrl: process.env.HARDHAT_RPC_URL || "http://127.0.0.1:8545",
    deployedAt: new Date().toISOString(),
  };

  const deploymentsDir = path.resolve(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });

  const deploymentPath = path.join(deploymentsDir, "localhost.json");
  fs.writeFileSync(deploymentPath, JSON.stringify(deployment, null, 2));

  const backendRoot = path.resolve(__dirname, "..", "..");
  const envPath = path.join(backendRoot, ".env.blockchain.generated");

  const senderPrivateKey = process.env.AUDIT_SENDER_PRIVATE_KEY || process.env.AUDIT_DEPLOYER_PRIVATE_KEY || "";

  const envText = [
    "# Auto-generated by backend/blockchain/scripts/deploy_and_export.js",
    "BLOCKCHAIN_ENABLED=true",
    `HARDHAT_RPC_URL=${deployment.rpcUrl}`,
    `AUDIT_CONTRACT_ADDRESS=${address}`,
    "AUDIT_CONTRACT_ABI_PATH=backend/blockchain/artifacts/contracts/AuditConsentRegistry.sol/AuditConsentRegistry.json",
    `AUDIT_SENDER_PRIVATE_KEY=${senderPrivateKey}`,
    "",
  ].join("\n");

  fs.writeFileSync(envPath, envText);

  console.log("AuditConsentRegistry deployed to:", address);
  console.log("Deployment record:", deploymentPath);
  console.log("Backend env snippet:", envPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
